services:
  web:
    build: 
        context: build
        dockerfile: Dockerfile
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data